// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_Restaurante.Data;

#nullable disable

namespace Proyecto_Restaurante.Migrations
{
    [DbContext(typeof(RestauranteDbContext))]
    [Migration("20260222154140_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_Restaurante.Models.Platillo", b =>
                {
                    b.Property<int>("PlatilloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlatilloId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("int");

                    b.HasKey("PlatilloId");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Platillos");

                    b.HasData(
                        new
                        {
                            PlatilloId = 1,
                            Descripcion = "Arroz, frijoles, ensalada, plátano maduro y pollo al horno.",
                            ImagenUrl = "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400",
                            Nombre = "Casado con Pollo",
                            Precio = 3500.00m,
                            RestauranteId = 1
                        },
                        new
                        {
                            PlatilloId = 2,
                            Descripcion = "Tradicional sopa costarricense con res, yuca, plátano y elote.",
                            ImagenUrl = "https://images.unsplash.com/photo-1547592180-85f173990554?w=400",
                            Nombre = "Olla de Carne",
                            Precio = 4200.00m,
                            RestauranteId = 1
                        },
                        new
                        {
                            PlatilloId = 3,
                            Descripcion = "Arroz con frijoles, culantro y chile dulce, servido con natilla.",
                            ImagenUrl = "https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=400",
                            Nombre = "Gallo Pinto",
                            Precio = 2000.00m,
                            RestauranteId = 1
                        },
                        new
                        {
                            PlatilloId = 4,
                            Descripcion = "Salsa de tomate, mozzarella fresca y albahaca sobre masa artesanal.",
                            ImagenUrl = "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400",
                            Nombre = "Pizza Margherita",
                            Precio = 6500.00m,
                            RestauranteId = 2
                        },
                        new
                        {
                            PlatilloId = 5,
                            Descripcion = "Pasta con huevo, queso pecorino, tocineta y pimienta negra.",
                            ImagenUrl = "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400",
                            Nombre = "Pasta Carbonara",
                            Precio = 5800.00m,
                            RestauranteId = 2
                        },
                        new
                        {
                            PlatilloId = 6,
                            Descripcion = "Capas de pasta, carne molida, bechamel y queso gratinado.",
                            ImagenUrl = "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=400",
                            Nombre = "Lasaña Boloñesa",
                            Precio = 6200.00m,
                            RestauranteId = 2
                        },
                        new
                        {
                            PlatilloId = 7,
                            Descripcion = "Carne de res 180g, lechuga, tomate, queso cheddar y pan brioche.",
                            ImagenUrl = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400",
                            Nombre = "Hamburguesa Clásica",
                            Precio = 4800.00m,
                            RestauranteId = 3
                        },
                        new
                        {
                            PlatilloId = 8,
                            Descripcion = "Papas crujientes con sal marina, servidas con salsa especial.",
                            ImagenUrl = "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400",
                            Nombre = "Papas Fritas",
                            Precio = 1800.00m,
                            RestauranteId = 3
                        },
                        new
                        {
                            PlatilloId = 9,
                            Descripcion = "Alitas de pollo bañadas en salsa BBQ ahumada, con vegetales.",
                            ImagenUrl = "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=400",
                            Nombre = "Alitas BBQ",
                            Precio = 4500.00m,
                            RestauranteId = 3
                        });
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.Restaurante", b =>
                {
                    b.Property<int>("RestauranteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestauranteId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCocina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RestauranteId");

                    b.ToTable("Restaurantes");

                    b.HasData(
                        new
                        {
                            RestauranteId = 1,
                            Descripcion = "Restaurante de comida costarricense tradicional",
                            Nombre = "La Sazón Tica",
                            TipoCocina = "Comida Típica"
                        },
                        new
                        {
                            RestauranteId = 2,
                            Descripcion = "Auténtica pizza y pasta italiana artesanal",
                            Nombre = "Pizza Napoli",
                            TipoCocina = "Italiana"
                        },
                        new
                        {
                            RestauranteId = 3,
                            Descripcion = "Las mejores hamburguesas artesanales del país",
                            Nombre = "Burger House",
                            TipoCocina = "Americana"
                        });
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.Platillo", b =>
                {
                    b.HasOne("Proyecto_Restaurante.Models.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });
#pragma warning restore 612, 618
        }
    }
}
