// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_Restaurante.Data;

#nullable disable

namespace Proyecto_Restaurante.Migrations
{
    [DbContext(typeof(RestauranteDbContext))]
    [Migration("20260219233215_SeedPlatillos")]
    partial class SeedPlatillos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_Restaurante.Models.Platillo", b =>
                {
                    b.Property<int>("PlatilloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlatilloId"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("int");

                    b.HasKey("PlatilloId");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Platillos");

                    b.HasData(
                        new
                        {
                            PlatilloId = 1,
                            Categoria = "Pizzas",
                            Descripcion = "Pizza tradicional con tomate, mozzarella y albahaca",
                            ImagenUrl = "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400",
                            Nombre = "Pizza Margarita",
                            Precio = 120.00m,
                            RestauranteId = 1
                        },
                        new
                        {
                            PlatilloId = 2,
                            Categoria = "Hamburguesas",
                            Descripcion = "Carne de res, lechuga, tomate, cebolla y queso cheddar",
                            ImagenUrl = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400",
                            Nombre = "Hamburguesa Clásica",
                            Precio = 95.00m,
                            RestauranteId = 1
                        },
                        new
                        {
                            PlatilloId = 3,
                            Categoria = "Ensaladas",
                            Descripcion = "Lechuga romana, aderezo césar, crutones y parmesano",
                            ImagenUrl = "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400",
                            Nombre = "Ensalada César",
                            Precio = 80.00m,
                            RestauranteId = 1
                        },
                        new
                        {
                            PlatilloId = 4,
                            Categoria = "Pastas",
                            Descripcion = "Fettuccine en salsa cremosa de queso parmesano",
                            ImagenUrl = "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=400",
                            Nombre = "Pasta Alfredo",
                            Precio = 110.00m,
                            RestauranteId = 1
                        },
                        new
                        {
                            PlatilloId = 5,
                            Categoria = "Mexicano",
                            Descripcion = "3 tacos con carne al pastor, piña, cilantro y cebolla",
                            ImagenUrl = "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400",
                            Nombre = "Tacos al Pastor",
                            Precio = 75.00m,
                            RestauranteId = 1
                        },
                        new
                        {
                            PlatilloId = 6,
                            Categoria = "Japonés",
                            Descripcion = "8 piezas de california roll con aguacate y surimi",
                            ImagenUrl = "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400",
                            Nombre = "Sushi Roll",
                            Precio = 130.00m,
                            RestauranteId = 1
                        });
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.Restaurante", b =>
                {
                    b.Property<int>("RestauranteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestauranteId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCocina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RestauranteId");

                    b.ToTable("Restaurantes");

                    b.HasData(
                        new
                        {
                            RestauranteId = 1,
                            Descripcion = "El mejor restaurante de la ciudad",
                            Nombre = "Restaurante Central",
                            TipoCocina = "Variada"
                        });
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.Platillo", b =>
                {
                    b.HasOne("Proyecto_Restaurante.Models.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });
#pragma warning restore 612, 618
        }
    }
}
